"""add hashed_password to user

Revision ID: d3b679bf919a
Revises: 2f9800b06e08
Create Date: 2026-04-29 10:21:14.264737

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3b679bf919a"
down_revision: Union[str, Sequence[str], None] = "2f9800b06e08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "users", sa.Column("hashed_password", sa.String(length=255), nullable=True)
    )
    # Временный плейсхолдер — реальные хеши проставит скрипт импорта
    op.execute("UPDATE users SET hashed_password = 'placeholder'")
    op.alter_column("users", "hashed_password", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
